### ISSUE TITLE
Profiling `TensorProductLinearGate`

### ISSUE THREAD

**Issue by mitkotak** [smsharma/eqnn-jax#4]
Was interested in adding `TensorProductLinearGate` to the profiling bank that I am building [here](https://github.com/atomicarchitects/FusionFail/tree/main) to document JAX fusion behavior:

- Is this the correct [code snippet](https://github.com/smsharma/eqnn-jax/blob/370e7edeeaee44399e87e49f58b9b915773e56c5/models/segnn.py#L20-L63) to tinker around with ?

- Are there any sharp bits or assumptions that would be good to know as I am comparing the kernel trace with `TensorProduct` and `TensorProductLinear` ?

Apologies for being vague. Just wanted to be extra cautious to make sure the profiles are helpful.

Thanks !

**Comment by smsharma** [comment]
Hey Mit, yeah that would be the right code for gated TP, go for it! We haven't been super careful with the nonlinearity options that go into `e3nn.gate`, I think that's the only potentially share bit there.
